name: Adam Laycock
markdown: redcarpet
highlighter: pygments
permalink: ":year/:month/:day/:title.html"
domain: arcath.github.io

sass:
  style: :compressed

prose:
  siteurl: "http://arcath.net/"
  media: "media/"
  ignore:
    - CNAME
    - Rakefile
