name: Adam Laycock
markdown: redcarpet
highlighter: pygments
permalink: ":year/:month/:day/:title.html"
domain: arcath.net

gem:
  - jekyll-feed

sass:
  style: :compressed

pygments:
  options: ['startinline']
