name: Adam Laycock
markdown: redcarpet
highlighter: pygments
permalink: ":year/:month/:day/:title.html"
domain: arcath.github.io

sass:
  style: :compressed

# Octopad Config

github_user: arcath
github_repo: arcath.github.io
github_branch: master
github_path: _posts/
