name: Adam Laycock
markdown: redcarpet
highlighter: pygments
permalink: ":year/:month/:day/:title.html"
domain: arcath.net
incremental: true
show_drafts: true

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap

sass:
  style: :compressed

highlighter:
  options: ['startinline']
