name: Adam Laycock
markdown: kramdown
highlighter: rouge
permalink: ":year/:month/:day/:title.html"
domain: arcath.net
#incremental: true
show_drafts: true

exclude:
  - node_modules

kramdown:
  input: GFM

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-coffeescript

gist:
  noscript: false

sass:
  style: :compressed

collections:
  - projects
